name: AWS data downloader
on:
  schedule:
    - cron: "0 23 */1 * *" # Every day at 23:00 UTC
  workflow_dispatch:

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps: 
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev -y
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
          
      - name: Setup renv
        run: |
          install.packages('renv')
        shell: Rscript {0}        
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Install dependencies
        run: renv::restore()
        shell: Rscript {0}
  
      - name: Run AWS data downloader for meteo
        run: source("R/get_meteo_data_from_aws.R")
        shell: Rscript {0}
      
      - name: Run AWS data downloader for tide
        run: source("R/get_tide_data.R")
        shell: Rscript {0}
      
      - name: Run data processing
        run: source("R/data_processing.R")
        shell: Rscript {0}
      
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "update data" && git push)